import { IAboutSectionTranslations } from '../../namepaces';

const about: IAboutSectionTranslations = {
  subtitle: 'explain like im five',
  title: 'About Hydranet',
  paragraphs: [
    'Hydranet DAO is a platform focused on Abstractive Interoperability – making fundamentally-incompatible decentralized crypto networks like Bitcoin and Ethereum talk fluently by way of Layer 3 abstraction with EVM-centric smart contracts and state channels, and Bitcoin/UTXO-based off-chain protocols like the Lightning Network.',
    'HDX is an Arbitrum token based on the (3,3) Protocol-owned Liquidity model pioneered by OlympusDAO.',
    'HDX rewards are generated by bonding funds to the protocol to provide it further liquidity and by staking to help secure the network. HDX will additionally serve as the meta-token of our Layer 3 DEX, being the end recipient of swaps from trading fees and DeFi services.',
  ],
};

export default about;
